[build]
  # Build settings for your frontend
  base = "ui"
  command = "npm run build"
  publish = "ui/dist"

[functions]
  # The location of your backend serverless functions
  directory = "../server/api"
  node_bundler = "esbuild"

[[redirects]]
  # Redirect /api/* requests to the Netlify functions
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
