[build]
  # Build settings for your frontend
  base = "ui"
  command = "npm --prefix ui run build"
  publish = "ui/dist"

[functions]
  # The location of your backend serverless functions
  directory = "server/api"
  node_bundler = "esbuild"
  external_node_modules = ["express", "cors", "dotenv", "nodemailer", "serverless-http"]

[[redirects]]
  # Redirect /api/* requests to the Netlify functions
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
