[build]
  command = "npm run build --prefix ui"
  publish = "ui/dist"

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run dev --prefix ui"
  port = 8888 
  targetPort = 5173 
  autoLaunch = false

[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200