[build]
  base = "ui"
  publish = "dist"
  command = "npm run build"
  functions = "../netlify/functions"

[dev]
  command = "cd ui && npm run dev" # Command to run your frontend dev server
  port = 8888 # Port where Netlify Dev server runs (default)
  targetPort = 5173 # Port where your Vite dev server is running
  autoLaunch = false

[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"      # SPA fallback
  status = 200